apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-3rd-connection-checker-argo-application
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/Supanut1911/nodejs-3party-connection-checker-application-configuration.git
    targetRevision: HEAD
    path: k8s/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-checker-argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
