apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3party-connection-checker
  namespace: nodejs-checker-argocd
  labels:
    app: 3party-connection-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3party-connection-checker
  template:
    metadata:
      labels:
        app: 3party-connection-checker
    spec:
      containers:
      - name: 3party-connection-checker
        image: devsupanut/nodejs-3party-checker:1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 4455
          name: web-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "/health"
            port: 4455
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: "/health"
            port: 4455
            scheme: HTTP


