thirdpartyConnectionChecker:
  namespace: nodejs-checker-argocd
  image: devsupanut/nodejs-3party-checker
  tag: 1.1
  replicas: 1
  port: 4455
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: thirdparty-connection-checker.0xnutx.space
  path: "/checker(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v1