apiVersion: v1
description: 3rd party connection checker Service Helm Chart
name: 3party-connection-checker
version: 1.0.0
appVersion: 1.0.0
home: https://3party-connection-checker.0xnutx.space/ratings
maintainers:
  - name: Developer
    email: 0xnutx@nutx.com