apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3party-connection-checker
  namespace: {{ .Values.3party-connection-checker.namespace }}
  labels:
    app: 3party-connection-checker
spec:
  replicas: {{ .Values.3party-connection-checker.replicas }}
  selector:
    matachLabels:
      app: 3party-connection-checker
    template:
      metadata:
        labels:
          app: 3party-connection-checker
    spec:
      containers:
      - name: 3party-connection-checker
        image: {{ .Values.3party-connection-checker.image }}:{{ .Values.3party-connection-checker.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.3party-connection-checker.port }}
          name: web-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.3party-connection-checker.healthCheckPath  }}
            port: {{ .Values.3party-connection-checker.port  }}
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: {{ .Values.3party-connection-checker.healthCheckPath  }}
            port: {{ .Values.3party-connection-checker.port  }}
            scheme: HTTP
