apiVersion: apps/v1
kind: Deployment
metadata:
  name: thirdparty-connection-checker
  namespace: {{ .Values.thirdparty-connection-checker.namespace}}
  labels:
    app: thirdparty-connection-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thirdparty-connection-checker
  template:
    metadata:
      labels:
        app: thirdparty-connection-checker
    spec:
      containers:
      - name: thirdparty-connection-checker
        image: devsupanut/nodejs-3party-checker:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.thirdparty-connection-checker.port}}
          name: web-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.thirdparty-connection-checker.healthCheckPath}}
            port: {{ .Values.thirdparty-connection-checker.port}}
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: {{ .Values.thirdparty-connection-checker.healthCheckPath}}
            port: {{ .Values.thirdparty-connection-checker.port}}
            scheme: HTTP
