apiVersion: v1
kind: Service
metadata:
  name: 3party-connection-checker
  namespace: {{ .Values.3party-connection-checker.namespace}}

  
spec:
  type: {{ .values.ingress.serviceType}}
  ports:
  - port: {{ .Values.3party-connection-checker.port }}
  selector:
    app: 3party-connection-checker