apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: thirdparty-connection-checker
  namespace: nodejs-checker-argocd

  
spec:
  rules:
  - host: thirdparty-connection-checker.0xnutx.space
    http:
      paths:
      - path: "/checker(/|$)(.*)"
        pathType: Prefix
        backend:
          service:
            name: thirdparty-connection-checker
            port:
              number: 4455
              