apiVersion: v1
kind: Service
metadata:
  name: 3party-connection-checker
  namespace: nodejs-checker-argocd

  
spec:
  type: ClusterIP
  ports:
  - port: 4455
  selector:
    app: 3party-connection-checker