apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    kubernetes.io/ingress.class: nginx
  {{- end }}
  {{- end }} 
  name: {{ .Release.Name}}
  namespace: {{ .Values.3party-connection-checker.namespace}}
spec:
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
      - path: {{ .Values.ingress.path}}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.3party-connection-checker.port }}
              