apiVersion: apps/v1
kind: Deployment
metadata:
  name: thirdparty-connection-checker
  namespace: {{ .Values.thirdparty-ConnectionChecker.namespace}}
  labels:
    app: thirdparty-connection-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thirdparty-connection-checker
  template:
    metadata:
      labels:
        app: thirdparty-connection-checker
    spec:
      containers:
      - name: thirdparty-connection-checker
        image: devsupanut/nodejs-3party-checker:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 4455
          name: web-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path:  "/health"
            port: 4455
            scheme: HTTP
        readinessProbe:
          httpGet:
            path:  "/health"
            port: 4455
            scheme: HTTP
