apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.thirdpartyConnectionChecker.namespace}}
spec:
  type: {{ .Values.ingress.serviceType}}
  ports:
  - port: {{ .Values.thirdpartyConnectionChecker.port}}
  selector:
    app: {{ .Release.Name }}